### ISSUE TITLE
Boot from sdboxv2

### ISSUE THREAD

**Issue by lcdiaz2106** [jbilander/SDBox-v2#6]
Hello
I recently buy this wonderful device.. would like to know if it's possible to boot with it.
Context: I have amiga 500 rev 6 with kickstart 3.1

let me know
many thanks

**Comment by jbilander** [comment]
Hi, the Amiga doesn't have the parallel port as a bootable device, but you can boot on a floppy that makes assign in the startup-sequence so that the system is loaded from the SDBox device.

Some links:

https://github.com/jbilander/sdbox/issues/11#issuecomment-1126999111

https://www.kernelcrash.com/blog/cheap-hard-drive-for-the-amiga-500-with-sdbox/2020/09/26/

**Comment by lcdiaz2106** [comment]
Hello
ok thanks for this aclaration.
I´ll try to do what you said.
Have a nice week end
